### ISSUE TITLE
Slot ID is wired to 00

### ISSUE THREAD

**Issue by bentprong** [bentprong/ocp_ttf#2]
Is this intentional?  It differs from Xavier is why I ask.

**Comment by bentprong** [comment]
Can we use this as a board ID?  Would require a change on next board spin to slot ID 01.  Need something to use to determine if NIC_PWR_GOOD/LED is wired up.

**Comment by jasonrock-dell** [comment]
if we spin the board we could possibly add jumper options

**Comment by bentprong** [comment]
I think I drove some confusion.  The slot ID is hard wired to 00, which is fine - it just differs from Xavier.  Didn't know if anyone caught that.  Don't you want to test other slot IDs?

As far as a **board rev ID** goes, Jon's suggestion to add 3 pins is good.  The pins will be internally pulled down to ground, and a resistor can be used to pull one+ up to ID the board rev.

**Comment by jasonrock-dell** [comment]
Agree.  if you also agree, can you close this.  otherwise let us know if we should change the slot id. thanks :)

**Comment by bentprong** [comment]
The slot ID is not actually "wired" to 0.  There are NP resistors. Closing as resolved.
