### ISSUE TITLE
Design change requests

### ISSUE THREAD

**Issue by bentprong** [bentprong/ocp_ttf#8]
1. Wire NIC_PWR_GOOD to unused GPIO pin.  Nice to have to verify that the 'power' command successfully powered up/down the NIC 3.0 card.

See also issue on heartbeat LED.  Nice to have to signal to user the state of the board.

**Comment by jasonrock-dell** [comment]
agree - would require a new board spin

**Comment by bentprong** [comment]
Summarizing requested changes:
1. Wire a LED between 3.3V and an NC MCU pin (heartbeat LED) - currently using pin on UART_P
2. Connect hot side of NIC PWR GOOD LED to an NC MCU pin (for feedback to firmware on NIC card power status - currently using pin on UART_P
3. Connect 3 NC MCU pins to provide a board ID.  These will be pulled low internal to the MCU then one should be pulled to 3.3V. I don't care which.

Rework on my board requested for item #3.  #1-2 already done but to the UART_P which is fine for now. Thanks.

**Comment by jasonrock-dell** [comment]
doing this in other tickets
